---
version: '3'

services:
    nginx:
      build: ./nginx
      image: nginx
      container_name: nginx
      ports:
        - "80:80"
      networks:
        - Train-network
      volumes:
        - test1code:/usr/share/test1.testycan.shop/html
        - test2code:/usr/share/test2.testycan.shop/html
        - test3code:/usr/share/test3.testycan.shop/html
      restart: always
      depends_on:
        - php
    php:
      build: ./php
      image: php:7-fpm
      container_name: php
      networks:
        - Train-network
      volumes:
        - test1code:/usr/share/test1.testycan.shop/html
        - test2code:/usr/share/test2.testycan.shop/html
        - test3code:/usr/share/test3.testycan.shop/html
      restart: always


volumes:
  test1code:
    driver: local
    driver_opts:
      type: none
      device: "/Users/anaselkassimi/Desktop/Codingchallenge/volumes/test1code"
      o: bind
  test2code:
    driver: local
    driver_opts:
      type: none
      device: "/Users/anaselkassimi/Desktop/Codingchallenge/volumes/test2code"
      o: bind
  test3code:
    driver: local
    driver_opts:
      type: none
      device: "/Users/anaselkassimi/Desktop/Codingchallenge/volumes/test3code"
      o: bind

networks:
    Train-network:
        name: Train-network
        driver: bridge
...
